import type { Readable } from 'node:stream';

// Bytes in, bytes out. Keys are generated by the service and contain no user input.
export interface StorageDriver {
  put(key: string, body: Buffer, contentType: string): Promise<void>;
  get(key: string): Promise<Readable>;
  delete(key: string): Promise<void>;
}
